### ISSUE TITLE
[wiki] Is it a goal for browsers to need explicit support SRC?

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/src#2]
From the **goals**:

> "At transaction time, if the merchant accepts the SRC payment method and **the browser implements it**, the user will be able to pay with an issued card."

This suggests there is an expectation that browsers will need to do some form of additional implementation beyond the existing standardised APIs (Payment Request and Payment Handler).

I would have expected the goal to be the opposite, for SRC to work without needing special implementation.

Should this read "and the browser implements PR API and PH API"?

**Comment by ianbjacobs** [comment]
I believe that's the intent. I have changed the text to "and the browser supports it (e.g., through Payment Request and payment handlers)."

It is conceivable that support could be built-in, but that's not a standardization matter.
