### ISSUE TITLE
Try to remain vendor neutral

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/src#35]
Some of the usability benefits are "In Chromium browsers". Don't get me wrong, I'm a bit fan and use Chrome a lot... but I'm worried that mentioning particular user experiences will shape the overall expectation for how the experience should be (limiting the ability to innovate at the UX level).

**Comment by ianbjacobs** [comment]
Hi @marcoscaceres,

That's a good point. Would a status note suffice, something like:

* In this document we refer to current implementation of APIs in Chromium browsers. These references are for illustrative purposes only and not meant to imply that all browsers must provide the same user experience.

Ian

**Comment by marcoscaceres** [comment]
Yeah, that would be fine.

**Comment by ianbjacobs** [comment]
Added. Thanks, @marcoscaceres!
